language: node_js

node_js:
  - 0.10

notifications:
  email:
    on_success: change
    on_failure: always

before_install:
  - npm install --quiet -g grunt-cli bower karma

before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
